Be explicit about what we expect with this test (and name it appropriately). It should compile (which it now does) and it should throw a NoSuchMethodError (which it currently does not).